<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<header>
    <ul>
        <li><a href="index/index">Naslovnica</a></li>
        <li><a href="form/index">Prijavi se</a></li>
        <li>Login (za admine)</li>
    </ul>
</header>

<main>
    <?php echo $content ?>
</main>

<footer>
    <p>&copy; PHP Akademija, 2016</p>
</footer>

</body>
</html>